[WIP] Migrate to new Gorm version
cloudfoundry-incubator/routing-api pull request #36
Opened 2023-08-24 17:21 UTC by ZPascal

fix https://github.com/cloudfoundry/routing-release/issues/164

**TODO:**

- [ ] Test it on a landscape (We've got the release not deployed on our landscapes)
- [ ] Fix the component tests

2026-03-09 16:12 UTC, ameowlia commented on db/db_sql.go
> +	clockVar := clock.NewClock()
Why did you rename clock?

2026-03-09 16:12 UTC, ameowlia commented on db/db_sql.go
> +		close(errorList)
why did you rename errors?

2026-03-09 16:23 UTC, ZPascal commented on db/db_sql.go
> +	clockVar := clock.NewClock()
The name conflicts with the used [import](https://github.com/ZPascal/routing-api/blob/ec96d0d9f02b0ed1405f4104a4f38962d6c24a7b/db/db_sql.go#L16). No AI name adaptation, just a finding from my linter/ IDE.

2026-03-09 16:24 UTC, ZPascal commented on db/db_sql.go
> +		close(errorList)
The name also conflicts with the used [import](https://github.com/ZPascal/routing-api/blob/ec96d0d9f02b0ed1405f4104a4f38962d6c24a7b/db/db_sql.go#L5). It's again a finding from the linter/ IDE.

2026-03-10 20:19 UTC, ZPascal commented on db/db_sql.go
> +		close(errorList)
I've reverted the change.

2026-03-10 20:19 UTC, ZPascal commented on db/db_sql.go
> +	clockVar := clock.NewClock()
I've reverted the change.

2026-04-20 20:53 UTC, ebroberson requested changes
Thank you for the contribution.  A few things I found that are mostly consistency issues.

2026-04-20 20:53 UTC, ebroberson commented on migration/V4_add_rg_uniq_idx_tcp_route_migration.go
> +	sqlDB.Client.Exec(indexSQL)
Looks like this should be `return ExecWithError` to be consistent with other migrations and to not hide a potential error.

2026-04-20 20:53 UTC, ebroberson commented on migration/V8_host_tls_port_tcp_default_zero_test.go
Another `ExecWithError` and handling the potential errors

2026-04-20 20:53 UTC, ebroberson commented on db/db_sql_test.go
> +							_, err = sqlDB.Client.Delete(&tcpRouteWithModel2)
Should be a `Where(...).Delete(...)`

2026-04-20 20:53 UTC, ebroberson commented on db/db_sql_test.go
> +							_, err = sqlDB.Client.Delete(&routeWithModel2)
Another `Where(...).Delete(...)`

2026-04-20 20:53 UTC, ebroberson commented on .gitignore
> +go.sum
Adding these is not consistent with other releases (e.g. diego-release/bbs, diego-release/credhub-cli)

2026-04-21 11:17 UTC, ZPascal commented on .gitignore
> +go.sum
done

2026-04-21 11:17 UTC, ZPascal commented on db/db_sql_test.go
> +							_, err = sqlDB.Client.Delete(&routeWithModel2)
done

2026-04-21 11:17 UTC, ZPascal commented on db/db_sql_test.go
> +							_, err = sqlDB.Client.Delete(&tcpRouteWithModel2)
done

2026-04-21 11:18 UTC, ZPascal commented on migration/V8_host_tls_port_tcp_default_zero_test.go
done

2026-04-21 11:18 UTC, ZPascal commented on migration/V4_add_rg_uniq_idx_tcp_route_migration.go
> +	sqlDB.Client.Exec(indexSQL)
done

2026-04-21 21:39 UTC, ebroberson commented on migration/V3_update_tcp_route_migration_test.go
> +		// Use direct SQL instead of GORM DropColumn to work around GORM bug
Could you expand on the GORM bug that requires the workaround?  Would like for someone reading the code to have a link (if possible) and maybe a short blurb about why this is needed.

2026-04-22 05:26 UTC, ZPascal commented on migration/V3_update_tcp_route_migration_test.go
> +		// Use direct SQL instead of GORM DropColumn to work around GORM bug
In GORM v2, `Statement.Table` is resolved lazily — only when a full query is actually built and executed. Calling `.Model(&TcpRouteMapping{})` stores the model in a new `gormClient`, but never triggers that resolution. So when `Migrator().DropColumn()` is called. `Statement.Table` is still `""`, and GORM silently targets a non-existent table, dropping nothing. (See: https://github.com/go-gorm/gorm/issues/5795)

**Fix:**
[Adjustment](https://github.com/cloudfoundry/routing-api/pull/36/changes/59e7bf41a202d292825f25172f46a03858760fc1) of the `DropColumn` function. 
```go
func (c *gormClient) DropColumn(name string) error {
	return c.db.Migrator().DropColumn(c.db.Statement.Model, name)
}
```

I actually intended to submit this change in a separate PR, but it actually fits quite well in the Gorm Migration PR.

2026-04-24 16:11 UTC, ebroberson approved these changes

2026-04-24 16:11 UTC, merged